color: true
dry-run: null
hookfiles: tests/dredd/hooks.php
language: vendor/bin/dredd-hooks-php
require: null
server: 'php -S 0.0.0.0:8080 -t public'
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: material-list-1.0.0.yaml
endpoint: 'http://0.0.0.0:8080'
