openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Material list'
  license:
    name: 'GNU General Public License v3.0'
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'

tags:
  - name: 'List'
    description: List handling
security:
  - BearerAuth: []
paths:
  /list/{listId}:
    get:
      tags:
        - List
      description: 'Get list with materials.'
      parameters:
        - $ref: '#/components/parameters/listId'
      responses:
        200:
          description: 'The list data is returned.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'
        404:
          description: 'Unknown list.'
        default:
          description: 'Unspecified error.'

  /list/{listId}/{materialId}:
    get:
      tags:
        - List
      description: 'Check existence of material on list.'
      parameters:
        - $ref: '#/components/parameters/listId'
        - $ref: '#/components/parameters/materialId'
      responses:
        201:
          description: 'The material exists on the list.'
        404:
          description: 'The list or material does not exist.'
        default:
          description: 'Unspecified error.'
    put:
      tags:
        - List
      description: 'Add material to the the list.'
      parameters:
        - $ref: '#/components/parameters/listId'
        - $ref: '#/components/parameters/materialId'
      responses:
        201:
          description: 'The material was successfully added to the list.'
        404:
          description: 'Unknown list.'
        default:
          description: 'Unspecified error.'
    delete:
      tags:
        - List
      description: 'Delete material from list.'
      parameters:
        - $ref: '#/components/parameters/listId'
        - $ref: '#/components/parameters/materialId'
      responses:
        204:
          description: 'Successfully removed.'
        404:
          description: 'Unknown list or material.'
        default:
          description: 'Unspecified error.'
  /migrate/{openlistId}:
    put:
      description: 'Migrate list for openlistId to current user.'
      parameters:
        - $ref: '#/components/parameters/openlistId'
      responses:
        204:
          description: 'Successfully migrated.'
        default:
          description: 'Unspecified error.'

components:
  parameters:
    listId:
      name: 'listId'
      in: 'path'
      description: 'The identifier of the list to return. Use "default" for the default list.'
      required: true
      example: 'default'
      schema:
        $ref: '#/components/schemas/ListId'
    materialId:
      name: 'materialId'
      in: 'path'
      description: 'The identifier of the material.'
      required: true
      example: '870970-basis:54871910'
      schema:
        $ref: '#/components/schemas/MaterialId'
    openlistId:
      name: 'openlistId'
      in: 'path'
      description: 'Openlist ID of a migrated list.'
      required: true
      example: 'anopenlistid'
      schema:
        $ref: '#/components/schemas/OpenlistId'

  schemas:
    ListId:
      description: 'List identifier. In the initial version, this can only be "default".'
      type: string
    MaterialId:
      description: 'A material identifier.'
      type: string
    List:
      type: object
      required:
        - id
        - materials
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/ListId'
        materials:
          type: array
          items:
            $ref: '#/components/schemas/MaterialId'
    OpenlistId:
      description: 'Openlist identifier.'
      type: string
      example: 'anopenlistid'
