version: "3"

tasks:
  check:
    desc: Run all tests and linters.
    deps:
      - lint
      - test

  test:
    desc: Run all tests
    summary: Runs all unit, behaviour and API tests.
    cmds:
      - docker compose exec app ./vendor/bin/phpunit
      - docker compose exec app ./vendor/bin/behat
      - docker compose exec app dredd

  lint:
    desc: Run all linters
    cmds:
      - docker compose exec app ./vendor/bin/phpcs
      - docker compose exec app php -d memory_limit=1G ./vendor/bin/phpstan
      - docker compose exec app speccy lint material-list.yaml
