apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress
data:
  enable-underscores-in-headers: "true"
  log-format-escape-json: "true"
  # See https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#httprequest and https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/
  log-format-upstream: '{"httpRequest":{"requestMethod":"$request_method","requestUrl":"$request_uri","requestSize":"$request_length","status":$status,"responseSize":"$upstream_response_length","userAgent":"$http_user_agent","remoteIp":"$the_real_ip","serverIp":"$remote_addr","referer":"$http_referer","latency":"$upstream_response_time"},"remoteUser":"$remote_user","timeLocal":"$time_local","bodyBytesSent":"$body_bytes_sent","requestTime":"$request_time","proxyUpstreamName":"$proxy_upstream_name","upstreamAddr":"$upstream_addr","upstreamStatus":"$upstream_status","reqId":"$req_id"}'
