# Default values for material-list-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: "prod"

ingress:
  enabled: true
  enableTLS: true
  cert: "letsencrypt"
  path: "/"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuTargetAverageUtilization: 70
  memoryTargetAverageUtilization: 80

app:
  image:
    version: "latest"
    imagePullPolicy: "IfNotPresent"
  db:
    host: '10.240.0.7'
    port: '3306'
    database: 'material-list'
  adgangsplatformen:
    driver: 'production'
  log_channel: 'stderr'
  url: 'prod.materiallist.dandigbib.org'
  timezone: 'UTC'
  cacheDriver: 'file'
  queueConnection: 'sync'
  cors_allow_origin: "*"
  replicas: 4
  php:
    type: "static"
    max_children: "14"
    memory_limit: "64M"
    opcache_memory_consumption: "32"
    opcache_max_accelerated_files: "20000"
    opcache_validate_timestamps: "0"

nginx:
  exporter:
    image:
      version: 0.11.0

