version: '3'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      
  nginx:
    image: ${DOCKER_REPO}/nginx:${NGINX_BUILD_TAG}
    depends_on:
    - release
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - 80
    volumes:
    - release-volume:/var/www/web:ro

  php-fpm:
    image: ${DOCKER_REPO}/php-fpm:${PHPFPM_BUILD_TAG}
    depends_on:
    - release
    environment:
      PHP_IDE_CONFIG: serverName=${VIRTUAL_HOST}
    volumes:
    - release-volume:/var/www/web:rw
  
  release:
    image: ${DOCKER_REPO}/material-list-release:${RELEASE}
    command: /opt/init-copy-source.sh
    volumes:
    - release-volume:/release:rw
    
volumes:
  release-volume: {}

