apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: material-list-ingress
spec:
  tls:
  - hosts:
    - prod.material-list.reload.dk
    secretName: prod-material-list-cert-api
  rules:
    - host: prod.material-list.reload.dk
      http:
        paths:
        - path: /
          backend:
            serviceName: material-list
            servicePort: http
