---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  APP_ADGANGSPLATFORMEN_DRIVER: {{ .Values.app.adgangsplatformen.driver | quote }}
  APP_LOG_CHANNEL: {{ .Values.app.log_channel | quote }}
  APP_DB_HOST: {{ .Values.app.db.host | quote }}
  APP_DB_PORT: {{ .Values.app.db.port | quote }}
  APP_DB_DATABASE: {{ .Values.app.db.database | quote }}
  APP_URL: {{ .Values.app.url | quote }}
  APP_TIMEZONE: {{ .Values.app.timezone | quote }}
  APP_CACHE_DRIVER: {{ .Values.app.cacheDriver | quote }}
  APP_QUEUE_CONNECTION: {{ .Values.app.queueConnection | quote }}
  PHP_PM_MAX_CHILDREN: {{ .Values.app.php.max_children | quote }}
  PHP_PM_START_SERVERS: {{ .Values.app.php.start_servers | quote }}
  PHP_PM_MIN_SPARE_SERVERS: {{ .Values.app.php.min_spare_servers | quote }}
  PHP_PM_MAX_SPARE_SERVERS: {{ .Values.app.php.max_spare_servers | quote }}
  PHP_REQUEST_SLOWLOG_TIMEOUT: {{ .Values.app.php.slowlog_timeout | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx-config
data:
  APP_PATH_PREFIX: {{ .Values.ingress.path | quote }}
  PHP_FPM_SERVER: "127.0.0.1"
  PHP_FPM_SERVER_PORT: "9000"
