{{- if eq .Values.env "prod" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_KEY: ''
  APP_ADGANGSPLATFORMEN_CLIENT_ID: ''
  APP_ADGANGSPLATFORMEN_CLIENT_SECRET: ''
  APP_DB_USERNAME: ''
  APP_DB_PASSWORD: ''
{{- end }}

{{- if eq .Values.env "stg" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_KEY: ''
  APP_ADGANGSPLATFORMEN_CLIENT_ID: ''
  APP_ADGANGSPLATFORMEN_CLIENT_SECRET: ''
  APP_DB_USERNAME: ''
  APP_DB_PASSWORD: ''
{{- end }}
